vim.keymap.set("n", "<leader>pv", ":Neotree action=focus position=left source=filesystem<CR>")
vim.keymap.set("n", "<leader>ls", ":Neotree action=focus position=float source=buffers<CR>")
vim.keymap.set("i", "jk", "<Esc>:w<CR>")
vim.keymap.set({"v", "n"}, "<C-v>", [["+p]])
vim.keymap.set({"v", "n"}, "<C-c>", [["+y]])
vim.keymap.set("n", "<C-h>", "<C-w>h") 
vim.keymap.set("n", "<C-j>", "<C-w>j") 
vim.keymap.set("n", "<C-k>", "<C-w>k") 
vim.keymap.set("n", "<C-l>", "<C-w>l") 

vim.keymap.set("t", "<C-h>", "<C-\\><C-n><C-w>h") 
vim.keymap.set("t", "<C-j>", "<C-\\><C-n><C-w>j") 
vim.keymap.set("t", "<C-k>", "<C-\\><C-n><C-w>k") 
vim.keymap.set("t", "<C-l>", "<C-\\><C-n><C-w>l")

-- Lazy-load telescope on first use
vim.keymap.set('n', '<leader>ff', function()
  local builtin = require('telescope.builtin')
  builtin.find_files()
end, {})
vim.keymap.set('n', '<leader>fl', function()
  local builtin = require('telescope.builtin')
  builtin.live_grep()
end, {})

-- Lazy-load terminal mappings on first use
vim.keymap.set({ "n", "x" }, "<leader>ts", function()
  local term_map = require("terminal.mappings")
  return term_map.operator_send()
end, { expr = true })
vim.keymap.set("n", "<leader>to", function()
  local term_map = require("terminal.mappings")
  term_map.toggle()
end)
vim.keymap.set("n", "<leader>tO", function()
  local term_map = require("terminal.mappings")
  term_map.toggle({ open_cmd = "enew" })
end)
vim.keymap.set("n", "<leader>tr", function()
  local term_map = require("terminal.mappings")
  term_map.run()
end)
vim.keymap.set("n", "<leader>tR", function()
  local term_map = require("terminal.mappings")
  term_map.run(nil, { layout = { open_cmd = "enew" } })
end)
vim.keymap.set("n", "<leader>tk", function()
  local term_map = require("terminal.mappings")
  term_map.kill()
end)
vim.keymap.set("n", "<leader>t]", function()
  local term_map = require("terminal.mappings")
  term_map.cycle_next()
end)
vim.keymap.set("n", "<leader>t[", function()
  local term_map = require("terminal.mappings")
  term_map.cycle_prev()
end)
vim.keymap.set("n", "<leader>tl", function()
  local term_map = require("terminal.mappings")
  term_map.move({ open_cmd = "belowright vnew" })
end)
vim.keymap.set("n", "<leader>tL", function()
  local term_map = require("terminal.mappings")
  term_map.move({ open_cmd = "botright vnew" })
end)
vim.keymap.set("n", "<leader>th", function()
  local term_map = require("terminal.mappings")
  term_map.move({ open_cmd = "belowright new" })
end)
vim.keymap.set("n", "<leader>tH", function()
  local term_map = require("terminal.mappings")
  term_map.move({ open_cmd = "botright new" })
end)
vim.keymap.set("n", "<leader>tf", function()
  local term_map = require("terminal.mappings")
  term_map.move({ open_cmd = "float" })
end)

-- LSP actions
vim.api.nvim_create_autocmd('LspAttach', {
  desc = 'LSP actions',
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(event)
    local opts = {buffer = event.buf}

    vim.keymap.set('n', 'K', '<cmd>lua vim.lsp.buf.hover()<cr>', opts)
    vim.keymap.set('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<cr>', opts)
    vim.keymap.set('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<cr>', opts)
    vim.keymap.set('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<cr>', opts)
    vim.keymap.set('n', 'go', '<cmd>lua vim.lsp.buf.type_definition()<cr>', opts)
    vim.keymap.set('n', 'gr', '<cmd>lua vim.lsp.buf.references()<cr>', opts)
    vim.keymap.set('n', 'gs', '<cmd>lua vim.lsp.buf.signature_help()<cr>', opts)
    vim.keymap.set('n', '<F2>', '<cmd>lua vim.lsp.buf.rename()<cr>', opts)
    vim.keymap.set({'n', 'x'}, '<F3>', '<cmd>lua vim.lsp.buf.format({async = true})<cr>', opts)
    vim.keymap.set('n', '<F4>', '<cmd>lua vim.lsp.buf.code_action()<cr>', opts)
  end,
})

-- Enter debug
vim.keymap.set('n', "<leader>bb", "Obreakpoint()<Esc>")

-- Lazy-load dbee on first use
vim.keymap.set('n', "<leader>db", function()
  local dbee = require("dbee")
  dbee.toggle()
end)

vim.keymap.set({'n', 'x', 'o'}, 's', '<Plug>(leap)')
vim.keymap.set('n', 'S', '<Plug>(leap-from-window)')

